version: '3'
services:
  agent:
    build:
      context: ./agent
    image: indigoframework/todo-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    depends_on:
    - store
  store:
    image: indigoframework/tmstore:0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [tmstore, -endpoint, "tcp://tmapp:46657"]
    depends_on:
    - tmapp
  tmapp:
    image: indigoframework/filetmpop:0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [filetmpop, -home, "/data/tendermint"]
    volumes:
    - ./validation:/data/validation
