version: "3"
services:
  agentui:
    image: stratumn/agent-ui:0.3.0
    env_file:
      - ./config/common.env
      - ./config/common.secret.env
      - ./config/dev.env
      - ./config/dev.secret.env
    ports:
      - "4000:4000"
  tmpopexplorer:
    image: stratumn/tmpop-explorer:0.3.0
    env_file:
      - ./config/common.env
      - ./config/common.secret.env
      - ./config/dev.env
      - ./config/dev.secret.env
    ports:
      - "8000:4000"
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - ./config/dev.env
      - ./config/dev.secret.env
    ports:
      - "3000:3000"
  store:
    env_file:
      - ./config/dev.env
      - ./config/dev.secret.env
  tmapp:
    user: root
    env_file:
      - ./config/dev.env
      - ./config/dev.secret.env
    ports:
      - "46656-46657:46656-46657"
    volumes:
      - ./tendermint:/data/tendermint
      - ./segments:/var/stratumn/filestore
networks:
  default:
    driver: bridge
    driver_opts:
      name: warehouse_dev
