version: '3'
services:
  agent:
    build:
      context: ./agent
    image: stratumn/part4-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    depends_on:
    - store
  store:
    image: indigocore/tmstore:0.3.0-rc1
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [tmstore, -endpoint, "tcp://tmnode:46657"]
    depends_on:
    - tmnode
  tmnode:
    image: indigocore/filetmpop:0.3.0-rc1
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    command: [filetmpop, -home, "/data/tendermint"]
    volumes:
    - ./validation:/data/validation
