version: "3"
services:
  agent:
    build:
      context: ./agent
    image: stratumn/warehouse-agent-js
    env_file:
      - ./config/common.env
      - ./config/common.secret.env
    volumes:
      - ./agent:/src/server
    depends_on:
      - store
  store:
    image: stratumn/tmstore:0.3.0
    env_file:
      - ./config/common.env
      - ./config/common.secret.env
    command: [tmstore, -endpoint, "tcp://tmapp:46657"]
    depends_on:
      - tmapp
  tmapp:
    image: stratumn/filetmpop:0.3.0
    env_file:
      - ./config/common.env
      - ./config/common.secret.env
    command: [filetmpop, -home, "/data/tendermint"]
    volumes:
      - ./validation:/data/validation
