version: '2'
services:
  agent:
    build:
      dockerfile: Dockerfile.test
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
  store:
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
  tmapp:
    user: root
    env_file:
    - ./config/test.env
    - ./config/test.secret.env
    volumes:
    - ./tendermint.test:/data/tendermint
networks:
  default:
    driver: bridge
    driver_opts:
        name: todo-tutorials-part1_test
